#log-path = "./logs"
# http-port = 80
url-path = ""

# gtoken配置文件
[gtoken]
    # 缓存模式 1 gcache 2 gredis
    cache-mode = 1
    # 是否支持多端登录
    multi-login = true

[server]
    Address          = ":80"
    ServerRoot       = "public"
    LogPath          = "./logs"
#    IndexFiles       = ["index.php", "main.php"]
    AccessLogEnabled = false
    ErrorLogEnabled  = true
    PProfEnabled     = true
#    SessionIdName    = "MySessionId"
#    SessionPath      = "/tmp/MySessionStoragePath"
#    SessionMaxAge    = "24h"
#    DumpRouterMap    = false

# title设置
[setting]
    title = "配置管理中心"

# WebServer管理
[admin]
    user = "admin"
    pass = "123"

# 数据库配置
[database]
    link = "mysql:root:123456@tcp(127.0.0.1:3306)/gmanager"
